version: 2.1
orbs:
  node: circleci/node@4.1.0


commands:
  install_packages:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  
  test:
    steps:
      - run:
          name: run jest test
          command: npm run test
      - store_artifacts:
          path: test-results.xml         
      - store_test_results:
          path: test-results.xml


  build_and_deploy_gh:
    steps:
      - run:
          name: build project
          command: npm run generate:gh-pages
      - run:
          name: Install and configure dependencies
          command: |
            npm ins tall gh-pages --save-dev
            git config user.email "hoang.vu@healthrfid.com"
            git config user.name "Hoang Vu"

      - add_ssh_keys:
          fingerprints:
            - "00:ed:6c:b8:24:c4:b4:b7:91:f8:74:ff:4a:ce:c1:b3"
      - run:
          name: Deploy docs to gh-pages branch
          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d dist'
  

jobs:
  test_and_build:
    executor: node/default
    steps:
      - checkout
      - install_packages
      - test
      - build_and_deploy_gh

workflows:
  test_and_deploy_GH:
    jobs:
      - test_and_build
