version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@6.15.3


commands:
  install_packages:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  
  test:
    steps:
      - run:
          name: run jest test
          command: npm run test
      - store_artifacts:
          path: test-report.html         
      - store_test_results:
          path: test-report.html


  build_and_deploy_gh:
    steps:
      - run:
          name: build project
          command: npm run generate:gh-pages
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages --save-dev
            git config user.email "hoang.vu@healthrfid.com"
            git config user.name "Hoang Vu"

      - add_ssh_keys:
          fingerprints:
            - "54:33:d2:9a:5d:b5:27:68:59:05:48:c3:48:bb:e9:b9"
      - run:
          name: Deploy docs to gh-pages branch
          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d dist'
  
  

jobs:
  test_and_build:
    executor: node/default
    steps:
      - checkout
      - install_packages
      - test
      - build_and_deploy_gh
  
  deploy_ecr: 
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: circleci-ecr-orb-demo
          tag: "$CIRCLE_SHA1"

workflows:
  test_and_deploy_GH:
    jobs:
      - test_and_build
  build_and_deploy_ecr:
    jobs:
      - deploy_ecr
