name: CI/CD for development branch

on:
  push:
    branches:
      - development
      - development_**
      - HRFID-**

jobs:
  build_and_test_development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4   
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '13.11.0'  

      - name: Find cache node
        uses: actions/cache@v2.1.6
        id: cache
        with:
          path: |
            ~/.npm
            node_modules
          key: dependency-cache-${{ hashFiles ('package.json') }}

      - name: Install dependency node
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run jest test
        run: npm run test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test_report
          path: test-report.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: coverage_report
          path: coverage    
