name: Limit PRs

on:
  pull_request:
    branches:
      - UAT

jobs:
  limit_master_pr:
    runs-on: ubuntu-latest
    name: Limits PR to UAT
    steps:
      - name: Limit Pull Requests
        id: limit_action
        uses: LukBukkit/action-pr-limits@v1.1.1
        with:
          whitelist: |
            SIT
