name: Limit PRs

on:
  pull_request:
    branches:
      - PROD

jobs:
  limit_prod_pr:
    runs-on: ubuntu-latest
    name: Limits PR to PROD
    steps:
      - name: Limit Pull Requests
        id: limit_action
        uses: LukBukkit/action-pr-limits@v1.1.1
        with:
          whitelist: |
            UAT
            HOTFIX_([a-zA-Z0-9]+)