name: Limit PRs

on:
  pull_request:
    branches:
      - CUSTOMER

jobs:
  limit_customer_pr:
    runs-on: ubuntu-latest
    name: Limits PR to customer
    steps:
      - name: Limit Pull Requests
        id: limit_action
        uses: LukBukkit/action-pr-limits@v1.1.1
        with:
          whitelist: |
            UAT
            UAT_([a-zA-Z0-9]+)
            HOTFIX_([a-zA-Z0-9]+)